services:
  app:
    build: .
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_CONTAINER_PORT}/${DB_DATABASE}"
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_CONTAINER_PORT}:5432"